#!/usr/bin/env bash
# Regression — issue #3483: every generated-fixture maker must reproduce, byte for
# byte, the fixtures committed beside it.
#
# WHY THIS EXISTS
# ---------------
# Two makers — sandbox/tests/fixtures/{adapter-walk,mup}/make-fixtures.php —
# exist so a grind's jq assertions run against documents the SHIPPED builders
# produced, not against what a fixture author remembered. That guarantee is
# only worth something while the script and the bytes agree, and nothing was
# checking that they did. They drifted for two releases:
#
#   - mup's maker stopped completing at all. #472 removed `checkpoint_at` from
#     RecoveryClaim's closed fact set (a clock inside the claim made
#     `plan_digest` a timestamp) and the caller was not updated, so the script
#     died on an InvalidArgumentException partway through writing;
#   - adapter-walk's maker ran to completion and produced four documents its
#     own grind rejected — projection keys spelled `principal`/`trust_root`
#     instead of `certification_principal`/`certification_trust_root`, a
#     hand-inserted undeclared-table line the renderer had since grown itself,
#     `option-prefix:wpforms_` where the product emits no trailing separator,
#     and `sha256:`-prefixed hashes where both producers emit bare 64-hex.
#
# Each time, the fixture BYTES were delta-edited instead and the maker was left
# broken, which is the failure mode this suite closes: the drift was invisible
# until someone re-ran a maker, and by then the fix was archaeology. #477's own
# commit message filed it as a follow-up rather than fixing it, which is how
# long it can hide.
#
# WHAT IS ASSERTED
# ----------------
#   1. REPRODUCTION. Every file a maker writes is byte-identical to the
#      committed fixture of the same name.
#   2. THE SAME SET. The names written and the names committed are the same set
#      (minus the maker itself). A fixture the maker stopped writing is drift in
#      the other direction: it would keep passing reproduction forever while no
#      longer being generated by anything.
#   3. DETERMINISM. Two runs into two different out-dirs both reproduce, which
#      is idempotence and out-dir independence in one — the makers take the
#      out-dir as argv[1] and resolve the repo from their own location, so a
#      run that only works in place would be a latent trap.
#
# What is NOT asserted is that a fixture records the right thing. That is the
# grinds' own `--self-check`, and it runs against these same bytes.
#
# WHY IT RUNS THE MAKERS IN FULL
# ------------------------------
# Measured on this estate: 0.06s per maker invocation, six of them (two per
# maker, plus the two self-tests), 0.70s wall for the whole suite. There is
# nothing to scope or sample — a partial guard would cost more in the reasoning
# about which half is covered than the whole one costs to run. If a third maker
# ever makes that untrue, the thing to cut is the determinism pass, not the
# reproduction pass: determinism is a property of the generator and only one
# run of it is needed to catch a drifted tree.
#
# The self-test at the bottom proves the comparison is non-vacuous by
# perturbing a scratch copy of the committed set and requiring the same code
# path to name what changed. It is not behind a flag: this suite ships green
# over an already-clean tree, so an `ok` line is only evidence if the machinery
# that printed it has just been shown to say FAIL. Same precedent as
# sandbox/tests/offline/assess-contract/regress_mup_leak_audit.sh, and it is
# also what `regress_suite_wiring.php` requires of the recipe shape — every
# sandbox/tests recipe is a bare `bash <file>.sh`, with no argument to forget.
#
# Offline: no docker, no WordPress, no network, no target, no pair.
set -euo pipefail
cd "$(dirname "$0")/../../.."   # -> sandbox/

pass() { printf '\033[1;32mok: %s\033[0m\n' "$*"; }
fail() { printf '\033[1;31mFAIL: %s\033[0m\n' "$*" >&2; FAILURES=$((FAILURES + 1)); }
say()  { printf '\n== %s ==\n' "$*"; }

FAILURES=0
[ "$#" -eq 0 ] || { printf 'usage: regress_fixture_makers.sh (no arguments)\n' >&2; exit 2; }

# `<label>|<maker path>`. Each path is a LITERAL rather than
# `tests/fixtures/$label/make-fixtures.php`, because tools/affected.php indexes
# a suite's dependencies by scanning its source for literal path tokens
# (af_extract_sandbox_relative_paths reads exactly this sandbox-relative
# spelling) — assembled from a variable, an edit to a maker would select no
# suite at all under `--changed`.
#
# The FIXTURES cannot be covered that way at any price: af_dir_signal_excluded
# drops every directory under sandbox/tests from the whole-tree signal on
# purpose, to stop one `cd` in one suite selecting a whole domain. So a fixture
# edit is seen by `make regress-offline-all` and not by `--changed`, which is
# the documented division of labour — `--changed` is iteration only.
MAKERS=(
  'adapter-walk|tests/fixtures/adapter-walk/make-fixtures.php'
  'mup|tests/fixtures/mup/make-fixtures.php'
)

SCRATCH="$(mktemp -d "${TMPDIR:-/tmp}/wprism-fixture-makers.XXXXXX")"
trap 'rm -rf -- "$SCRATCH"' EXIT INT TERM

# reproduces <label> <maker-script> <expected-dir> <out-dir>
#
# Prints its own diagnostic and returns 1; it never touches FAILURES, because
# the self-test below calls it EXPECTING a non-zero return and a counter
# mutated inside the function would have to be undone by the caller. Scoring
# stays with the caller, which is the only place that knows which outcome is
# the passing one.
#
# On failure it names every file that disagreed rather than the first: a maker
# that moved one shared key touches a dozen fixtures, and "assess-report.s1.json
# differs" alone would send the reader hunting for a fixture-specific cause that
# does not exist.
#
# Drifted names accumulate in a newline-delimited string rather than an array —
# stock macOS ships bash 3.2, where `${#arr[@]}` on an empty array is an
# unbound-variable error under `set -u`, and the empty case is the one this
# function is in every time it passes.
reproduces() {
  local label="$1" maker="$2" expected="$3" out="$4"
  mkdir -p "$out"
  if ! php "$maker" "$out" >/dev/null; then
    printf '\033[1;31mFAIL: %s: the maker did not run to completion (php %s <out-dir>)\033[0m\n' \
      "$label" "$maker" >&2
    return 1
  fi

  local wrote committed
  wrote="$(cd "$out" && ls -A | sort)"
  # The maker is the one file in the fixture directory it does not write.
  committed="$(cd "$expected" && ls -A | grep -vFx make-fixtures.php | sort)"
  if [ "$wrote" != "$committed" ]; then
    printf '\033[1;31mFAIL: %s: the generated set and the committed set differ:\033[0m\n' "$label" >&2
    diff <(printf '%s\n' "$committed") <(printf '%s\n' "$wrote") | sed 's/^/    /' >&2
    return 1
  fi

  local drifted="" name count
  while IFS= read -r name; do
    [ -n "$name" ] || continue
    cmp -s "$out/$name" "$expected/$name" || drifted="$drifted$name"$'\n'
  done <<<"$wrote"

  if [ -n "$drifted" ]; then
    count="$(printf '%s' "$drifted" | grep -c '')"
    printf '\033[1;31mFAIL: %s: the maker no longer reproduces %s committed fixture(s):\033[0m\n' \
      "$label" "$count" >&2
    printf '%s' "$drifted" | sed 's/^/    /' >&2
    printf '  Regenerate them with: php %s\n' "$maker" >&2
    printf '  then re-run the grind'"'"'s --self-check before committing the new bytes.\n' >&2
    return 1
  fi

  return 0
}

say "each maker reproduces its committed fixtures"
for entry in "${MAKERS[@]}"; do
  maker="${entry%%|*}"
  SCRIPT="${entry#*|}"
  DIR="$(dirname "$SCRIPT")"
  [ -f "$SCRIPT" ] || { fail "$maker: $SCRIPT is missing"; continue; }
  if reproduces "$maker" "$SCRIPT" "$DIR" "$SCRATCH/$maker.a"; then
    pass "$maker: every committed fixture is what its maker writes today"
  else
    fail "$maker: the maker and its committed fixtures have drifted apart"
  fi
done

say "the makers are deterministic and out-dir independent"
for entry in "${MAKERS[@]}"; do
  maker="${entry%%|*}"
  SCRIPT="${entry#*|}"
  [ -f "$SCRIPT" ] || continue
  # Compared against the FIRST run rather than against the committed set, so
  # this reports non-determinism on its own terms: a maker that drifted from
  # the tree fails the block above once, and must not fail here as well for a
  # reason ("two runs disagree") that is not what happened.
  mkdir -p "$SCRATCH/$maker.b"
  if ! php "$SCRIPT" "$SCRATCH/$maker.b" >/dev/null; then
    fail "$maker: the maker did not run to completion on its second run"
    continue
  fi
  if diff -r "$SCRATCH/$maker.a" "$SCRATCH/$maker.b" >"$SCRATCH/$maker.diff" 2>&1; then
    pass "$maker: a second run into a different out-dir writes the same bytes"
  else
    fail "$maker: two runs of one maker into two out-dirs disagree:
$(sed 's/^/    /' "$SCRATCH/$maker.diff")"
  fi
done

say "self-test: the comparison actually fails on drift"
# A copy of the committed set with one deliberate defect, standing in for the
# expected side. The makers are unchanged and the repository is untouched:
# what is on trial is whether `reproduces` can tell two byte sets apart.
MUTANT="$SCRATCH/mutant"
cp -R tests/fixtures/mup "$MUTANT"
printf 'x' >>"$MUTANT/assess-report.pass.json"
if reproduces 'self-test (mutated fixture)' tests/fixtures/mup/make-fixtures.php \
    "$MUTANT" "$SCRATCH/selftest.a" 2>/dev/null; then
  fail "self-test: a mutated fixture was accepted as reproduced"
else
  pass "a one-byte fixture change is caught and named"
fi

# The other direction: a fixture the maker does not write must be caught by
# the set comparison, not silently ignored the way a per-file loop would.
ORPHAN="$SCRATCH/orphan"
cp -R tests/fixtures/mup "$ORPHAN"
printf '{}\n' >"$ORPHAN/assess-report.never-generated.json"
if reproduces 'self-test (orphan fixture)' tests/fixtures/mup/make-fixtures.php \
    "$ORPHAN" "$SCRATCH/selftest.b" 2>/dev/null; then
  fail "self-test: a committed fixture no maker writes was accepted"
else
  pass "a committed fixture no maker writes is caught and named"
fi

if [ "$FAILURES" -ne 0 ]; then
  printf '\n\033[1;31mFIXTURE MAKERS: %d FAILURE(S)\033[0m\n' "$FAILURES" >&2
  exit 1
fi
printf '\nFIXTURE MAKERS OK\n'
