<?php
declare(strict_types=1);

namespace WPrism;

/**
 * GENERATED by tools/shipped-identity-inventory.php — do not edit.
 *
 * Dependency-free runtime projection of the package/platform source tree.
 * Regenerate with: php tools/shipped-identity-inventory.php
 */
final class ShippedIdentityInventory
{
    /** @var list<string> */
    public const ADAPTER_NAMES = [
        'acf',
        'advanced-editor-tools',
        'block-visibility',
        'change-wp-admin-login',
        'classic-editor',
        'code-snippets',
        'contact-form-7',
        'core',
        'download-manager',
        'elementor',
        'ninja-forms',
        'paid-memberships-pro',
        'polylang',
        'qi-blocks',
        'rank-math',
        'redirection',
        'speculation-rules',
        'the-events-calendar',
        'visual-portfolio',
        'woocommerce',
        'wordpress-popup',
        'wpforms-lite',
        'wprism-agency-cpt',
        'wps-hide-login',
        'yoast',
        'yoast-duplicate-post',
    ];
}
