<?php
declare(strict_types=1);

// DUO-3297: product-path certification of compile-bounded local/offload
// journaling, encrypted before-images, crash retry, exact inverse, and fresh
// read-after-restore under the signed external rollback receipt.

require dirname(__DIR__, 2) . '/recovery/rollback-control.php';
require dirname(__DIR__, 2) . '/cli/src/Transport/Transport.php';
require dirname(__DIR__, 2) . '/cli/src/Transport/SshTransport.php';
require dirname(__DIR__, 2) . '/cli/src/Recovery/RollbackAuthority.php';

use Duo\Orchestrator\RollbackAuthority;
use Duo\Orchestrator\SshTransport;
use Duo\Recovery\RecoveryExecutor;
use Duo\Recovery\RollbackControl;
use Duo\Recovery\UploadBundle;

function ub_fail(string $m): never { fwrite(STDERR, "FAIL: $m\n"); exit(1); }
function ub_ok(bool $c,string $m): void { if(!$c)ub_fail($m);echo "ok: $m\n"; }
function ub_refuses(callable $f,string $m): void { try{$f();}catch(Throwable $e){echo "ok: $m [{$e->getMessage()}]\n";return;}ub_fail($m); }
function ub_write(string $p,string $b,int $mode=0600): void { $d=dirname($p);if(!is_dir($d))mkdir($d,0700,true);if(file_put_contents($p,$b)!==strlen($b))ub_fail("write $p");chmod($p,$mode); }
function ub_remove(string $p): void { if(is_link($p)||is_file($p)){@unlink($p);return;}if(!is_dir($p))return;foreach(scandir($p)?:[]as$n)if($n!=='.'&&$n!=='..')ub_remove($p.'/'.$n);@rmdir($p); }
function ub_signed(string $root,array $payload,string $kind,string $keyId,string $secret): array { $p=tempnam(sys_get_temp_dir(),'duo-upload-request-');if($p===false)ub_fail('temp');ub_write($p,RollbackControl::canonical(RollbackControl::sign($payload,$keyId,$secret))."\n");try{return match($kind){'exclusion'=>RecoveryExecutor::handleExclusionRequest($root,$p),'uploads'=>UploadBundle::handleRequest($root,$p)};}finally{@unlink($p);} }
function ub_authority(string $root,array $event,?array $receipt,string $keyId,string $secret): array { $request=['action'=>$receipt===null?'append':'claim','event'=>RollbackControl::sign($event,$keyId,$secret),'receipt'=>$receipt===null?null:RollbackControl::sign($receipt,$keyId,$secret)];$p=tempnam(sys_get_temp_dir(),'duo-authority-');if($p===false)ub_fail('temp');ub_write($p,RollbackControl::canonical($request)."\n");try{return RollbackControl::handleRequest($root,$p);}finally{@unlink($p);} }
function ub_event(array $receipt,array $status,string $state,string $opStatus,string $opId,int $attempt,string $input,string $result,string $time): array { $seconds=strtotime($time);return ['artifact_hash'=>$receipt['artifact_hash'],'attempt'=>$attempt,'claim_epoch'=>1,'claim_expires_at'=>gmdate('Y-m-d\TH:i:s\Z',(int)$seconds+60),'claimant'=>'worker-a','format'=>RollbackControl::EVENT_FORMAT,'generation'=>$receipt['generation'],'input_sha256'=>$input,'operation_id'=>$opId,'operation_status'=>$opStatus,'owner'=>$receipt['owner'],'previous_event_sha256'=>$status['head_event_sha256']??str_repeat('0',64),'receipt_id'=>$receipt['receipt_id'],'result_sha256'=>$result,'sequence'=>isset($status['sequence'])?(int)$status['sequence']+1:1,'signing_key_id'=>$receipt['signing_key_id'],'state'=>$state,'target_id'=>$receipt['target_id'],'timestamp'=>$time]; }
function ub_input(string $path,array $receipt,array $prepared,string $operation): string { $v=['artifact_hash'=>$receipt['artifact_hash'],'desired_inventory_sha256'=>$prepared['desired_inventory_sha256'],'format'=>'duo-upload-operation/v1','generation'=>$receipt['generation'],'operation'=>$operation,'owner'=>$receipt['owner'],'prior_inventory_sha256'=>$prepared['prior_inventory_sha256'],'receipt_id'=>$receipt['receipt_id'],'target_id'=>$receipt['target_id'],'uploads_inventory_sha256'=>$prepared['uploads_inventory_sha256']];ub_write($path,RollbackControl::canonical($v)."\n");$h=hash_file('sha256',$path);return is_string($h)?$h:ub_fail('input hash'); }

$tmp=sys_get_temp_dir().'/duo-upload-bundle-'.bin2hex(random_bytes(8));
$pair=sodium_crypto_sign_keypair();$secret=sodium_crypto_sign_secretkey($pair);$public=sodium_crypto_sign_publickey($pair);$keyId='upload-test';
try {
  mkdir($tmp,0700,true);$root=$tmp.'/site/.duo/control';$initial=RollbackControl::initialize($root);RollbackControl::installPublicKey($root,$keyId,base64_encode($public));
  $uploads=$tmp.'/uploads';$offload=$tmp.'/offload';$media=$tmp.'/media';mkdir($uploads.'/2026/08',0755,true);mkdir($offload.'/2026/08',0755,true);mkdir($media,0700,true);
  $localOld="local-prior\n";$localDerivativeOld="local-thumb-prior\n";$remoteOld="remote-prior\n";ub_write($uploads.'/2026/08/photo.jpg',$localOld,0644);ub_write($uploads.'/2026/08/photo-100x100.jpg',$localDerivativeOld,0644);ub_write($offload.'/2026/08/cloud.jpg',$remoteOld,0644);
  $localNew="local-desired\n";$remoteNew="remote-desired\n";$localBlob=hash('sha256',$localNew).'.jpg';$remoteBlob=hash('sha256',$remoteNew).'.jpg';ub_write($media.'/'.$localBlob,$localNew);ub_write($media.'/'.$remoteBlob,$remoteNew);
  $inventory=[
    ['attachment_uuid'=>'11111111-1111-4111-8111-111111111111','derivative_basename_prefix'=>'photo-','derivative_directory'=>'2026/08','media_blob'=>$localBlob,'original_path'=>'2026/08/photo.jpg','original_sha256'=>hash('sha256',$localNew)],
    ['attachment_uuid'=>'22222222-2222-4222-8222-222222222222','derivative_basename_prefix'=>'cloud-','derivative_directory'=>'remote/2026/08','media_blob'=>$remoteBlob,'original_path'=>'remote/2026/08/cloud.jpg','original_sha256'=>hash('sha256',$remoteNew)],
  ];
  $state=$tmp.'/provider-state';$provider=dirname(__DIR__).'/tests/fixtures/upload-provider.php';$exclusion=dirname(__DIR__).'/tests/fixtures/recovery-exclusion-provider.php';$adapter=dirname(__DIR__).'/tests/fixtures/recovery-adapter.php';$encKey=$tmp.'/upload.key';ub_write($encKey,random_bytes(SODIUM_CRYPTO_SECRETBOX_KEYBYTES));
  $adapters=[];foreach(['code_restore','database_restore','prior_verify','storage_restore']as$n)$adapters[$n]=[PHP_BINARY,$adapter];
  $config=['adapters'=>$adapters,'exclusion_provider'=>[PHP_BINARY,$exclusion,$tmp.'/exclusion.json'],'format'=>'duo-recovery-config/v1','timeout_seconds'=>5,'upload_provider'=>[PHP_BINARY,$provider,$state,$uploads,$offload,$media,$encKey]];
  $configPath=$tmp.'/recovery.json';ub_write($configPath,RollbackControl::canonical($config)."\n");RecoveryExecutor::configureFromFile($root,$configPath);touch($state.'.leak');ub_refuses(fn()=>RecoveryExecutor::probe($root),'provider credential fields are rejected from evidence and logs');unlink($state.'.leak');$probe=RecoveryExecutor::probe($root);ub_ok(($probe['uploads']['supports_local']??false)===true&&($probe['uploads']['supports_offload']??false)===true,'local and offload provider contracts preflight explicitly');$readyStatus=RecoveryExecutor::decorateStatus($root,RollbackControl::status($root));ub_ok(!array_key_exists('automatic_upload_rollback',$readyStatus),'status drops configuration-only automatic upload boolean before a receipt is bound');
  $artifact=hash('sha256','artifact');$receiptId=str_repeat('a',48);$target=$initial['target_id'];$time='2020-01-01T00:00:00Z';$retention='2020-01-02T00:00:00Z';
  $ex=ub_signed($root,['action'=>'acquire','artifact_hash'=>$artifact,'claim_epoch'=>1,'claimant'=>'worker-a','format'=>'duo-exclusion-request/v1','generation'=>1,'owner'=>'controller:test','receipt_id'=>$receiptId,'target_id'=>$target,'timestamp'=>$time],'exclusion',$keyId,$secret);
  $prepare=['action'=>'prepare','artifact_hash'=>$artifact,'claim_epoch'=>1,'claimant'=>'worker-a','format'=>'duo-upload-bundle-request/v1','generation'=>1,'inventory'=>$inventory,'owner'=>'controller:test','receipt_id'=>$receiptId,'retention_until'=>$retention,'target_id'=>$target,'timestamp'=>$time];
  // Unsafe filesystem types and crash-partial artifacts are refused before a
  // receipt can exist, then the exact same immutable request is retryable.
  symlink($tmp.'/missing',$uploads.'/2026/08/photo-evil.jpg');ub_refuses(fn()=>ub_signed($root,$prepare,'uploads',$keyId,$secret),'symlink derivative is refused during pre-mutation inventory');unlink($uploads.'/2026/08/photo-evil.jpg');
  mkdir($uploads.'/2026/08/photo-directory.jpg');ub_refuses(fn()=>ub_signed($root,$prepare,'uploads',$keyId,$secret),'non-regular derivative type is refused during inventory');rmdir($uploads.'/2026/08/photo-directory.jpg');
  $badInventory=$inventory;$badInventory[0]['original_path']='../escape.jpg';ub_refuses(fn()=>ub_signed($root,array_replace($prepare,['inventory'=>$badInventory]),'uploads',$keyId,$secret),'traversal in compiled upload declarations is rejected before provider mutation');
  touch($state.'.unsupported');ub_refuses(fn()=>ub_signed($root,$prepare,'uploads',$keyId,$secret),'unsupported provider path blocks the generation before mutation');
  foreach(['kill-before-prepare','kill-after-inventory','kill-after-cipher']as$b){touch($state.'.'.$b);ub_refuses(fn()=>ub_signed($root,$prepare,'uploads',$keyId,$secret),"prepare crash $b remains retryable");}
  $prepared=ub_signed($root,$prepare,'uploads',$keyId,$secret);ub_ok(preg_match('/^[0-9a-f]{64}$/',$prepared['uploads_inventory_sha256'])===1,'prepared upload evidence has an immutable receipt hash');
  $priorInventory=json_decode((string)file_get_contents(dirname($root).'/rollback/'.$receiptId.'/artifacts/prior-inventory.json'),true);$remotePrior=array_values(array_filter($priorInventory['entries']??[],fn($e)=>($e['path']??'')==='remote/2026/08/cloud.jpg'))[0]??null;ub_ok(is_array($remotePrior)&&str_starts_with((string)($remotePrior['version_id']??''),'version-'),'offload prior state carries a provider-native version id as well as exact before-image evidence');
  $cipher=file_get_contents(dirname($root).'/rollback/'.$receiptId.'/artifacts/before-images.enc');ub_ok(is_string($cipher)&&!str_contains($cipher,$localOld)&&!str_contains($cipher,$localDerivativeOld),'local before-images are encrypted at rest');
  $metadataPath=dirname($root).'/rollback/'.$receiptId.'/upload-bundle-metadata.json';$metadataBytes=file_get_contents($metadataPath);ub_write($metadataPath,(string)$metadataBytes." ");
  $receipt=['adapter_versions_sha256'=>hash('sha256','adapters'),'artifact_hash'=>$artifact,'checkpoint_sha256'=>hash('sha256','checkpoint'),'claim_ttl_seconds'=>60,'created_at'=>$time,'encryption_key_id'=>'kms-test','exclusion_token_sha256'=>$ex['token_sha256'],'format'=>'duo-rollback-receipt/v1','generation'=>1,'ledger_session_sha256'=>hash('sha256','ledger'),'lifecycle_receipts_sha256'=>hash('sha256','lifecycle'),'owner'=>'controller:test','prior_code_descriptor_sha256'=>hash('sha256','code'),'prior_verifier_inputs_sha256'=>hash('sha256','verify'),'receipt_id'=>$receiptId,'resources_inventory_sha256'=>hash('sha256','resources'),'retention_until'=>$retention,'runtime_fingerprints_sha256'=>hash('sha256','runtime'),'signing_key_id'=>$keyId,'target_id'=>$target,'uploads_inventory_sha256'=>$prepared['uploads_inventory_sha256']];
  $first=ub_event($receipt,[],'prepared','state_transition','promotion-claim',1,hash('sha256',RollbackControl::canonical($receipt)),str_repeat('0',64),$time);ub_refuses(fn()=>ub_authority($root,$first,$receipt,$keyId,$secret),'tampered upload metadata blocks signed generation claim');ub_write($metadataPath,(string)$metadataBytes);
  $status=ub_authority($root,$first,$receipt,$keyId,$secret);ub_ok($status['state']==='prepared','signed receipt claims exact prepared upload bundle');
  $status=ub_authority($root,ub_event($receipt,$status,'promoting','state_transition','promotion-start',1,hash('sha256','promote'),str_repeat('0',64),'2020-01-01T00:00:01Z'),null,$keyId,$secret);
  $applyInput=$tmp.'/apply.json';$applyHash=ub_input($applyInput,$receipt,$prepared,'apply_desired');$status=ub_authority($root,ub_event($receipt,$status,'promoting','prepared','storage_apply',1,$applyHash,str_repeat('0',64),'2020-01-01T00:00:02Z'),null,$keyId,$secret);
  $paths=['2026/08/photo.jpg','2026/08/photo-150x150.jpg','remote/2026/08/cloud.jpg','remote/2026/08/cloud-150x150.jpg'];
  foreach($paths as$i=>$path){$edge=$i%2===0?'before':'after';touch($state.'.kill-'.$edge.'-write-'.hash('sha256',$path));ub_refuses(fn()=>RecoveryExecutor::execute($root,'storage_apply','storage_apply',1,'worker-a',1,$applyInput),"crash $edge local/offload publish $path is retryable");}
  touch($state.'.report-undeclared');ub_refuses(fn()=>RecoveryExecutor::execute($root,'storage_apply','storage_apply',1,'worker-a',1,$applyInput),'provider-reported undeclared derivative blocks completion');unlink($state.'.report-undeclared');
  $applied=RecoveryExecutor::execute($root,'storage_apply','storage_apply',1,'worker-a',1,$applyInput);ub_ok(file_get_contents($uploads.'/2026/08/photo.jpg')===$localNew&&file_get_contents($offload.'/2026/08/cloud.jpg')===$remoteNew,'desired local/offload originals and derivatives publish through journaled provider');
  $reportBytes=(string)file_get_contents(dirname($root).'/rollback/'.$receiptId.'/artifacts/mutation-report.json');$report=json_decode($reportBytes,true);$derivatives=array_filter($report['operations']??[],fn($op)=>str_contains((string)($op['path']??''),'150x150'));ub_ok(count($derivatives)===2&&preg_match('/secret|credential|signed.?url|access.?token/i',$reportBytes)!==1,'metadata generation reports every bounded derivative without secrets');
  $status=ub_authority($root,ub_event($receipt,$status,'promoting','completed','storage_apply',1,$applyHash,$applied['result_sha256'],'2020-01-01T00:00:03Z'),null,$keyId,$secret);
  $status=ub_authority($root,ub_event($receipt,$status,'rollback_pending','state_transition','verification-failed',1,hash('sha256','failure'),str_repeat('0',64),'2020-01-01T00:00:04Z'),null,$keyId,$secret);
  $status=ub_authority($root,ub_event($receipt,$status,'rolling_back','state_transition','rollback-start',1,hash('sha256','rollback'),str_repeat('0',64),'2020-01-01T00:00:05Z'),null,$keyId,$secret);
  $restoreInput=$tmp.'/restore.json';$restoreHash=ub_input($restoreInput,$receipt,$prepared,'restore_prior');$status=ub_authority($root,ub_event($receipt,$status,'rolling_back','prepared','storage_restore',1,$restoreHash,str_repeat('0',64),'2020-01-01T00:00:06Z'),null,$keyId,$secret);
  // Exact absence receipts never delete a concurrently replaced object.
  ub_write($offload.'/2026/08/cloud-150x150.jpg',"concurrent-writer\n",0644);ub_refuses(fn()=>RecoveryExecutor::execute($root,'storage_restore','storage_restore',1,'worker-a',1,$restoreInput),'changed created derivative is not deletion authority');ub_write($offload.'/2026/08/cloud-150x150.jpg',"DERIVATIVE:".hash('sha256',$remoteNew)."\n",0644);
  foreach([['before','2026/08/photo.jpg','restore'],['after','remote/2026/08/cloud.jpg','restore'],['before','2026/08/photo-150x150.jpg','delete'],['after','remote/2026/08/cloud-150x150.jpg','delete']]as[$edge,$path,$verb]){touch($state.'.kill-'.$edge.'-'.$verb.'-'.hash('sha256',$path));ub_refuses(fn()=>RecoveryExecutor::execute($root,'storage_restore','storage_restore',1,'worker-a',1,$restoreInput),"crash $edge $verb boundary $path is retryable");}
  $restored=RecoveryExecutor::execute($root,'storage_restore','storage_restore',1,'worker-a',1,$restoreInput);ub_ok(file_get_contents($uploads.'/2026/08/photo.jpg')===$localOld&&file_get_contents($uploads.'/2026/08/photo-100x100.jpg')===$localDerivativeOld&&!file_exists($uploads.'/2026/08/photo-150x150.jpg')&&file_get_contents($offload.'/2026/08/cloud.jpg')===$remoteOld&&!file_exists($offload.'/2026/08/cloud-150x150.jpg'),'restore atomically recovers prior bytes and deletes only unchanged proven-created paths');
  ub_ok($restored['result_sha256']===$prepared['prior_inventory_sha256'],'fresh provider process verifies exact prior originals and derivative inventory');
  $status=ub_authority($root,ub_event($receipt,$status,'rolling_back','completed','storage_restore',1,$restoreHash,$restored['result_sha256'],'2020-01-01T00:00:07Z'),null,$keyId,$secret);
  $status=ub_authority($root,ub_event($receipt,$status,'verifying_prior','state_transition','prior-verify-start',1,hash('sha256','verify-prior'),str_repeat('0',64),'2020-01-01T00:00:08Z'),null,$keyId,$secret);
  $priorInput=$tmp.'/prior-verify.json';ub_write($priorInput,RollbackControl::canonical(['checkpoint_sha256'=>$receipt['checkpoint_sha256'],'operation'=>'prior_verify'])."\n");$priorHash=(string)hash_file('sha256',$priorInput);
  $status=ub_authority($root,ub_event($receipt,$status,'verifying_prior','prepared','prior_verify',1,$priorHash,str_repeat('0',64),'2020-01-01T00:00:09Z'),null,$keyId,$secret);
  $priorResult=RecoveryExecutor::execute($root,'prior_verify','prior_verify',1,'worker-a',1,$priorInput);
  $status=ub_authority($root,ub_event($receipt,$status,'verifying_prior','completed','prior_verify',1,$priorHash,$priorResult['result_sha256'],'2020-01-01T00:00:10Z'),null,$keyId,$secret);
  $status=ub_authority($root,ub_event($receipt,$status,'rolled_back','state_transition','prior-verified',1,hash('sha256','prior-pass'),hash('sha256','prior-pass-result'),'2020-01-01T00:00:11Z'),null,$keyId,$secret);ub_ok(!empty($status['terminal']),'verified prior state reaches terminal authority');
  ub_refuses(fn()=>ub_signed($root,array_replace($prepare,['action'=>'delete','inventory'=>null,'timestamp'=>'2020-01-01T12:00:00Z']),'uploads',$keyId,$secret),'retention blocks early before-image deletion');
  $deleted=ub_signed($root,array_replace($prepare,['action'=>'delete','inventory'=>null,'timestamp'=>'2020-01-03T00:00:00Z']),'uploads',$keyId,$secret);$afterDelete=RecoveryExecutor::decorateStatus($root,RollbackControl::status($root));ub_ok(($deleted['deleted']??false)===true&&($afterDelete['uploads']['deleted']??false)===true,'terminal retained upload bundle deletion stays status-verifiable and auditable');
  $deletedAgain=ub_signed($root,array_replace($prepare,['action'=>'delete','inventory'=>null,'timestamp'=>'2020-01-03T00:00:00Z']),'uploads',$keyId,$secret);ub_ok($deletedAgain===$deleted,'terminal upload bundle deletion retry is idempotent');

  // Controller API: the caller supplies the compiled rows, never a trusted
  // receipt digest. The SSH authority prepares remotely and owns that field.
  $controllerHost=$tmp.'/controller-host';$controllerRoot=$controllerHost.'/.duo/control';RollbackControl::initialize($controllerRoot);RollbackControl::installPublicKey($controllerRoot,$keyId,base64_encode($public));$runtime=$controllerRoot.'/recovery-runtime';mkdir($runtime,0700,true);foreach(['CanonicalJson.php','AtomicStore.php','ProtocolLock.php','ProviderClient.php','rollback-control.php','RecoveryExecutor.php','CheckpointBundle.php','CodeRelease.php','UploadBundle.php','EffectBundle.php']as$f)copy(dirname(__DIR__,2).'/recovery/'.$f,$runtime.'/'.$f);
  $controllerState=$tmp.'/controller-provider';$controllerConfig=$config;$controllerConfig['exclusion_provider']=[PHP_BINARY,$exclusion,$tmp.'/controller-exclusion.json'];$controllerConfig['upload_provider']=[PHP_BINARY,$provider,$controllerState,$uploads,$offload,$media,$encKey];$controllerConfigPath=$tmp.'/controller-config.json';ub_write($controllerConfigPath,RollbackControl::canonical($controllerConfig)."\n");RecoveryExecutor::configureFromFile($controllerRoot,$controllerConfigPath);
  $signing=$tmp.'/controller-signing.key';ub_write($signing,base64_encode($secret)."\n");$fake=$tmp.'/fake-bin';mkdir($fake,0700);ub_write($fake.'/ssh',"#!/bin/sh\n[ \"\$1\" = -T ] && shift\nshift\nexec /bin/sh -c \"\$1\"\n",0700);ub_write($fake.'/scp',"#!/bin/sh\nsrc=\$1\ndest=\$2\ntarget=\${dest#*:}\ncp \"\$src\" \"\$target\"\n",0700);putenv('PATH='.$fake.':'.getenv('PATH'));
  $transport=new SshTransport('upload-controller',['transport'=>'ssh','host'=>'fixture-host','wp_path'=>$tmp.'/unused-wordpress','repo_path'=>$controllerHost,'rollback_key_id'=>$keyId,'rollback_signing_key'=>$signing,'rollback_recovery'=>['adapters'=>$adapters,'exclusion_provider'=>[PHP_BINARY,$exclusion,$tmp.'/controller-exclusion.json'],'timeout_seconds'=>5,'upload_provider'=>[PHP_BINARY,$provider,$controllerState,$uploads,$offload,$media,$encKey]]]);
  $authority=new RollbackAuthority($transport);$claim=$authority->claim(['adapter_versions_sha256'=>hash('sha256','controller-adapters'),'artifact_hash'=>hash('sha256','controller-artifact'),'checkpoint_sha256'=>hash('sha256','manual-checkpoint'),'claim_ttl_seconds'=>60,'created_at'=>'2020-02-01T00:00:00Z','encryption_key_id'=>'manual-key','lifecycle_receipts_sha256'=>hash('sha256','controller-lifecycle'),'owner'=>'controller:upload-test','prior_code_descriptor_sha256'=>hash('sha256','manual-code'),'prior_verifier_inputs_sha256'=>hash('sha256','manual-verifier'),'resources_inventory_sha256'=>hash('sha256','controller-resources'),'retention_until'=>'2020-02-02T00:00:00Z','runtime_fingerprints_sha256'=>hash('sha256','controller-runtime'),'ledger_session_sha256'=>hash('sha256','controller-ledger'),'upload_inventory'=>$inventory],'controller-worker','2020-02-01T00:00:00Z');
  ub_ok(($claim['status']['state']??'')==='prepared'&&preg_match('/^[0-9a-f]{64}$/',(string)($claim['receipt']['uploads_inventory_sha256']??''))===1,'SSH controller prepares and binds provider-owned upload evidence before receipt publication');
  echo "PASS: upload/media mutations are compile-bounded, receipt-journaled, restorable, and freshly verified\n";
} finally { sodium_memzero($secret);ub_remove($tmp); }
