<?php
declare(strict_types=1);

namespace Duo\Orchestrator;

require_once __DIR__ . '/../Onboarding/Adopt.php';
require_once __DIR__ . '/AdoptCommand.php';
require_once __DIR__ . '/AssessCommand.php';
require_once __DIR__ . '/HostProcess.php';
require_once __DIR__ . '/InitCommand.php';
require_once __DIR__ . '/StatusCommand.php';

/** Guided composition of the existing adoption, assessment, and init gates. */
final class OnboardCommand {
    /**
     * @param list<string> $extra everything after `<env>`
     * @param ?array{
     *   adopt?:callable(EnvironmentDriver,array,string):int,
     *   assess?:callable(EnvironmentDriver,array,string):int,
     *   init?:callable(EnvironmentDriver,array):int,
     *   status?:callable(EnvironmentDriver):int,
     *   handoff_preflight?:callable(EnvironmentDriver,string,string):void,
     *   handoff?:callable(EnvironmentDriver,string,string):string
     * } $steps
     */
    public static function run(
        EnvironmentDriver $driver,
        array $extra,
        string $sourceRoot,
        ?array $steps = null
    ): int {
        try {
            [$initArgs, $gitUrl, $handoffOnly] = self::options($extra);
            $workspace = AssessCommand::siteRepo(getcwd() ?: '.');
            if ($handoffOnly && $gitUrl === null) {
                throw new \RuntimeException('--handoff-only requires --git-url=<url>');
            }
        } catch (\Throwable $error) {
            fwrite(STDERR, 'duo: onboard: ' . $error->getMessage() . "\n");
            return 1;
        }

        $adopt = $steps['adopt'] ?? static fn(EnvironmentDriver $target, array $args, string $root): int =>
            AdoptCommand::run($target, $args, $root);
        $assess = $steps['assess'] ?? static fn(EnvironmentDriver $target, array $args, string $root): int =>
            AssessCommand::run($target, $args, $root);
        $status = $steps['status'] ?? static fn(EnvironmentDriver $environment): int => StatusCommand::run(
            $environment,
            [],
            static function (string $code, string $message, string $remediation): void {
                fwrite(STDERR, "[$code] $message\n");
                fwrite(STDERR, "remedy: $remediation\n");
            },
            static function (array $refusal): void {
                fwrite(STDERR, (string) ($refusal['message'] ?? 'status refused') . "\n");
            },
            static fn(): bool => true
        );
        $init = $steps['init'] ?? static fn(EnvironmentDriver $target, array $args): int =>
            InitCommand::run(
                $target,
                $args,
                static function (array $refusal): void {
                    $message = (string) ($refusal['message'] ?? 'initialization refused');
                    fwrite(STDERR, "duo: $message\n");
                },
                $status,
                static fn(): mixed => fgets(STDIN),
                false
            );
        $handoffPreflight = $steps['handoff_preflight'] ?? self::preflightHandoff(...);
        $handoff = $steps['handoff'] ?? self::publishAndCheckout(...);

        if ($handoffOnly) {
            try {
                $branch = $handoff($driver, $workspace, (string) $gitUrl);
            } catch (\Throwable $error) {
                fwrite(STDERR, 'duo: onboard handoff: ' . $error->getMessage() . "\n");
                return 1;
            }
            self::renderHandoffSuccess($sourceRoot, $driver, $branch);
            return 0;
        }

        if ($gitUrl !== null) {
            try {
                // Credentials, remote emptiness, local generated bytes and
                // origin consistency are all answerable before adopt/init.
                $handoffPreflight($driver, $workspace, $gitUrl);
            } catch (\Throwable $error) {
                fwrite(STDERR, 'duo: onboard handoff preflight: ' . $error->getMessage() . "\n");
                return 1;
            }
        }

        echo "Onboarding 1/3: install Duo transactionally.\n";
        $exit = $adopt($driver, [], $sourceRoot);
        if ($exit !== 0) {
            return $exit;
        }
        echo "Onboarding 2/3: assess the installed site without changing managed state.\n";
        $exit = $assess($driver, [], $sourceRoot);
        if ($exit !== 0) {
            return $exit;
        }
        echo "Onboarding 3/3: review and initialize the managed baseline.\n";
        $exit = $init($driver, $initArgs);
        if ($exit !== 0) {
            return $exit;
        }

        if ($gitUrl !== null) {
            try {
                $branch = $handoff($driver, $workspace, $gitUrl);
            } catch (\Throwable $error) {
                fwrite(STDERR, 'duo: onboard handoff: ' . $error->getMessage() . "\n");
                return 1;
            }
            self::renderHandoffSuccess($sourceRoot, $driver, $branch);
        } else {
            $cli = realpath($sourceRoot . '/cli/duo') ?: $sourceRoot . '/cli/duo';
            echo "Initialized successfully. Publish it later without repeating adopt/assess/init:\n";
            echo '  ' . escapeshellarg($cli) . ' onboard ' . escapeshellarg($driver->name())
                . " --handoff-only --git-url=<empty-remote-url>\n";
            echo "The URL must be reachable with Git credentials from both this controller and the WordPress target.\n";
        }
        return 0;
    }

    /** @return array{0:list<string>,1:?string,2:bool} */
    public static function options(array $extra): array {
        $init = [];
        $gitUrl = null;
        $handoffOnly = false;
        foreach ($extra as $arg) {
            if ($arg === '--handoff-only') {
                if ($handoffOnly) {
                    throw new \RuntimeException('--handoff-only was supplied more than once');
                }
                $handoffOnly = true;
                continue;
            }
            if (is_string($arg) && str_starts_with($arg, '--git-url=')) {
                if ($gitUrl !== null) {
                    throw new \RuntimeException('--git-url was supplied more than once');
                }
                $gitUrl = substr($arg, strlen('--git-url='));
                if ($gitUrl === '' || preg_match('/[\x00-\x1f\x7f]/', $gitUrl) === 1) {
                    throw new \RuntimeException('--git-url requires a non-empty URL without control bytes');
                }
                continue;
            }
            $init[] = $arg;
        }
        if ($handoffOnly && $init !== []) {
            throw new \RuntimeException('--handoff-only accepts no init flags');
        }
        return [$init, $gitUrl, $handoffOnly];
    }

    private static function preflightHandoff(
        EnvironmentDriver $driver,
        string $workspace,
        string $gitUrl
    ): void {
        self::assertLocalBoundary($workspace);
        self::assertLocalOrigin($workspace, $gitUrl);
        $local = HostProcess::run(['git', 'ls-remote', $gitUrl]);
        if ($local['exit'] !== 0) {
            throw new \RuntimeException('controller cannot authenticate to the Git remote: ' . trim($local['stderr']));
        }
        if (trim($local['stdout']) !== '') {
            throw new \RuntimeException('Git remote is not empty; use a new empty remote for initial publication');
        }
        $q = static fn(string $value): string => escapeshellarg($value);
        $target = $driver->captureRaw('git ls-remote ' . $q($gitUrl));
        if ($target['exit'] !== 0) {
            throw new \RuntimeException('target cannot authenticate to the Git remote: ' . trim($target['stderr']));
        }
        if (trim($target['stdout']) !== '') {
            throw new \RuntimeException('Git remote became non-empty during target credential preflight');
        }
    }

    private static function publishAndCheckout(
        EnvironmentDriver $driver,
        string $workspace,
        string $gitUrl
    ): string {
        self::assertLocalBoundary($workspace);
        $initialBranch = self::assertPristineLocalCheckout($workspace);
        self::assertLocalOrigin($workspace, $gitUrl);
        $repo = $driver->repoPath();
        $q = static fn(string $value): string => escapeshellarg($value);
        $script = 'set -eu; repo=' . $q($repo) . '; url=' . $q($gitUrl) . '; '
            . 'test -d "$repo/.git"; '
            . 'branch=$(git -C "$repo" symbolic-ref --quiet --short HEAD) || '
            . '{ echo "target Git worktree has detached HEAD" >&2; exit 1; }; '
            . 'git check-ref-format --branch "$branch" >/dev/null; '
            . 'origin_missing=0; if git -C "$repo" remote get-url origin >/dev/null 2>&1; then '
            . 'test "$(git -C "$repo" remote get-url --all origin)" = "$url" || '
            . '{ echo "target origin URL does not match --git-url" >&2; exit 1; }; '
            . 'test "$(git -C "$repo" remote get-url --push --all origin)" = "$url" || '
            . '{ echo "target origin push URL does not match --git-url" >&2; exit 1; }; '
            . 'else origin_missing=1; fi; '
            . 'remote=$(git -C "$repo" ls-remote "$url" "refs/heads/$branch"); '
            . 'git -C "$repo" add .gitignore site.duo.json code state media; '
            . 'if ! git -C "$repo" diff --cached --quiet; then '
            . 'git -C "$repo" -c user.name=duo -c user.email=duo@example.test commit -m "duo: initial managed baseline"; fi; '
            . 'head=$(git -C "$repo" rev-parse HEAD); '
            . 'if [ -n "$remote" ] && [ "${remote%%[[:space:]]*}" != "$head" ]; then '
            . 'echo "remote branch $branch is not the initialized target revision" >&2; exit 1; fi; '
            . 'git -C "$repo" push "$url" "HEAD:refs/heads/$branch"; '
            . 'if [ "$origin_missing" -eq 1 ]; then git -C "$repo" remote add origin "$url"; fi; '
            . 'git -C "$repo" fetch origin "$branch"; '
            . 'git -C "$repo" branch --set-upstream-to="origin/$branch" "$branch" >/dev/null; '
            . 'printf "DUO_HANDOFF %s %s\\n" "$branch" "$head"';
        $target = $driver->captureRaw($script);
        if ($target['exit'] !== 0) {
            throw new \RuntimeException('target Git publish failed: ' . trim($target['stderr']));
        }
        if (preg_match('/^DUO_HANDOFF ([^\s]+) ([a-f0-9]{40})$/m', $target['stdout'], $published) !== 1) {
            throw new \RuntimeException('target Git publish returned no branch/revision receipt');
        }
        $branch = $published[1];
        $revision = $published[2];

        self::ensureLocalOrigin($workspace, $gitUrl);
        $remoteRef = 'refs/remotes/origin/' . $branch;
        $fetch = HostProcess::run([
            'git', '-C', $workspace, 'fetch', '--no-tags', 'origin',
            '+refs/heads/' . $branch . ':' . $remoteRef,
        ]);
        if ($fetch['exit'] !== 0) {
            throw new \RuntimeException('local Git fetch failed: ' . trim($fetch['stderr']));
        }
        $fetched = HostProcess::run(['git', '-C', $workspace, 'rev-parse', '--verify', $remoteRef]);
        if ($fetched['exit'] !== 0 || trim($fetched['stdout']) !== $revision) {
            throw new \RuntimeException('fetched branch moved after the target publication receipt; local boundary was not changed');
        }

        self::assertLocalBoundary($workspace);
        $token = bin2hex(random_bytes(16));
        $backups = [
            $workspace . '/site.duo.json' => $workspace . '/.git/duo-handoff-site-' . $token,
            $workspace . '/.gitignore' => $workspace . '/.git/duo-handoff-ignore-' . $token,
        ];
        $moved = [];
        try {
            foreach ($backups as $path => $backup) {
                if (!rename($path, $backup)) {
                    throw new \RuntimeException("could not stage local generated boundary $path");
                }
                $moved[$path] = $backup;
            }
            $checkout = HostProcess::run(
                ['git', '-C', $workspace, 'checkout', '-b', $branch, '--track', $remoteRef]
            );
            if ($checkout['exit'] !== 0) {
                throw new \RuntimeException('local Git checkout failed: ' . trim($checkout['stderr']));
            }
            $head = HostProcess::run(['git', '-C', $workspace, 'rev-parse', 'HEAD']);
            if ($head['exit'] !== 0 || trim($head['stdout']) !== $revision) {
                throw new \RuntimeException('local checkout does not match the target publication receipt');
            }
        } catch (\Throwable $error) {
            try {
                self::restorePristineCheckout($workspace, $initialBranch, $branch, $moved);
            } catch (\Throwable $rollback) {
                throw new \RuntimeException(
                    $error->getMessage() . '; local checkout rollback failed: ' . $rollback->getMessage()
                );
            }
            throw $error;
        }
        foreach ($backups as $backup) {
            if (is_file($backup) && !is_link($backup) && !unlink($backup)) {
                throw new \RuntimeException("checkout succeeded but generated-boundary backup cleanup failed: $backup");
            }
        }
        return $branch;
    }

    private static function assertLocalBoundary(string $workspace): void {
        self::assertGeneratedFile($workspace . '/site.duo.json', Adopt::repositorySeedBytes());
        self::assertGeneratedFile($workspace . '/.gitignore', Adopt::repositoryGitignoreBytes());
    }

    private static function assertPristineLocalCheckout(string $workspace): string {
        if (is_link($workspace . '/.git') || !is_dir($workspace . '/.git')
            || is_link($workspace . '/.duo-envs.json') || !is_file($workspace . '/.duo-envs.json')) {
            throw new \RuntimeException('local workspace control boundary is not ordinary');
        }
        $entries = array_values(array_diff(scandir($workspace) ?: [], ['.', '..']));
        sort($entries, SORT_STRING);
        if ($entries !== ['.duo-envs.json', '.git', '.gitignore', 'site.duo.json']) {
            throw new \RuntimeException('local workspace changed before handoff; expected only connect-generated entries');
        }
        $head = HostProcess::run(['git', '-C', $workspace, 'rev-parse', '--verify', 'HEAD']);
        $heads = HostProcess::run(['git', '-C', $workspace, 'for-each-ref', '--format=%(refname)', 'refs/heads']);
        $index = HostProcess::run(['git', '-C', $workspace, 'ls-files']);
        $branch = HostProcess::run(['git', '-C', $workspace, 'symbolic-ref', '--quiet', '--short', 'HEAD']);
        if ($head['exit'] === 0 || $heads['exit'] !== 0 || trim($heads['stdout']) !== ''
            || $index['exit'] !== 0 || trim($index['stdout']) !== ''
            || $branch['exit'] !== 0 || trim($branch['stdout']) === '') {
            throw new \RuntimeException('local workspace Git state is no longer the empty connect boundary');
        }
        return trim($branch['stdout']);
    }

    /** @param array<string,string> $backups */
    private static function restorePristineCheckout(
        string $workspace,
        string $initialBranch,
        string $publishedBranch,
        array $backups
    ): void {
        foreach ([
            ['git', '-C', $workspace, 'symbolic-ref', 'HEAD', 'refs/heads/' . $initialBranch],
            ['git', '-C', $workspace, 'read-tree', '--empty'],
            ['git', '-C', $workspace, 'clean', '-fdx', '-e', '.duo-envs.json', '-e', '.gitignore', '-e', 'site.duo.json'],
            ['git', '-C', $workspace, 'update-ref', '-d', 'refs/heads/' . $publishedBranch],
        ] as $command) {
            $result = HostProcess::run($command);
            if ($result['exit'] !== 0) {
                throw new \RuntimeException(trim($result['stderr']) ?: 'Git could not restore the empty workspace');
            }
        }
        foreach ($backups as $path => $backup) {
            if (is_link($path) || (file_exists($path) && !is_file($path))) {
                throw new \RuntimeException("checked-out boundary is not an ordinary file: $path");
            }
            if (is_file($path) && !unlink($path)) {
                throw new \RuntimeException("could not remove checked-out boundary: $path");
            }
            if (!is_file($backup) || is_link($backup) || !rename($backup, $path)) {
                throw new \RuntimeException("could not restore generated boundary: $path");
            }
        }
        self::assertLocalBoundary($workspace);
        self::assertPristineLocalCheckout($workspace);
    }

    private static function assertLocalOrigin(string $workspace, string $gitUrl): void {
        $origin = HostProcess::run(['git', '-C', $workspace, 'config', '--get', 'remote.origin.url']);
        if ($origin['exit'] === 0 && trim($origin['stdout']) !== $gitUrl) {
            throw new \RuntimeException('local origin URL does not match --git-url');
        }
        if ($origin['exit'] !== 0 && $origin['exit'] !== 1) {
            throw new \RuntimeException('could not inspect the local origin: ' . trim($origin['stderr']));
        }
    }

    private static function ensureLocalOrigin(string $workspace, string $gitUrl): void {
        $origin = HostProcess::run(['git', '-C', $workspace, 'config', '--get', 'remote.origin.url']);
        if ($origin['exit'] === 0) {
            if (trim($origin['stdout']) !== $gitUrl) {
                throw new \RuntimeException('local origin URL does not match --git-url');
            }
            return;
        }
        if ($origin['exit'] !== 1) {
            throw new \RuntimeException('could not inspect the local origin: ' . trim($origin['stderr']));
        }
        $add = HostProcess::run(['git', '-C', $workspace, 'remote', 'add', 'origin', $gitUrl]);
        if ($add['exit'] !== 0) {
            throw new \RuntimeException('could not configure local origin: ' . trim($add['stderr']));
        }
    }

    private static function renderHandoffSuccess(
        string $sourceRoot,
        EnvironmentDriver $driver,
        string $branch
    ): void {
        $cli = realpath($sourceRoot . '/cli/duo') ?: $sourceRoot . '/cli/duo';
        echo "Published the initialized target baseline and checked out branch $branch in this workspace.\n";
        echo "Next: inspect the initialized target through the configured environment:\n";
        echo '  ' . escapeshellarg($cli) . ' assess ' . escapeshellarg($driver->name()) . "\n";
        echo "Capture always writes to the target repo_path ({$driver->repoPath()}), not this local checkout.\n";
        echo "Before feature-branch capture, point or materialize the target to that branch; see docs/guides/daily-workflow.md.\n";
        echo "Disposable preview creation additionally requires two configured environments and providers; see docs/guides/release.md.\n";
    }

    private static function assertGeneratedFile(string $path, string $expected): void {
        if (is_link($path) || !is_file($path) || file_get_contents($path) !== $expected) {
            throw new \RuntimeException("local generated boundary changed; refusing to replace $path");
        }
    }

}
