<?php
declare(strict_types=1);

namespace Duo\Orchestrator;

require_once __DIR__ . '/../Onboarding/Adopt.php';
require_once __DIR__ . '/AdoptCommand.php';
require_once __DIR__ . '/AssessCommand.php';
require_once __DIR__ . '/HostProcess.php';
require_once __DIR__ . '/InitCommand.php';
require_once __DIR__ . '/StatusCommand.php';

/** Guided composition of the existing adoption, assessment, and init gates. */
final class OnboardCommand {
    private const GIT_TRANSFER_TIMEOUT_MILLISECONDS = 900000;
    private const GIT_TRANSFER_OUTPUT_LIMIT_BYTES = 8388608;
    private const TARGET_PROBE_TIMEOUT_MILLISECONDS = 120000;
    private const TARGET_PROBE_OUTPUT_LIMIT_BYTES = 1048576;
    /**
     * @param list<string> $extra everything after `<env>`
     * @param ?array{
     *   adopt?:callable(EnvironmentDriver,array,string):int,
     *   assess?:callable(EnvironmentDriver,array,string):int,
     *   init?:callable(EnvironmentDriver,array):int,
     *   status?:callable(EnvironmentDriver):int,
     *   handoff_preflight?:callable(EnvironmentDriver,string,string):void,
     *   handoff?:callable(EnvironmentDriver,string,string):string
     * } $steps
     */
    public static function run(
        EnvironmentDriver $driver,
        array $extra,
        string $sourceRoot,
        ?array $steps = null
    ): int {
        try {
            [$initArgs, $gitUrl, $handoffOnly] = self::options($extra);
            $workspace = AssessCommand::siteRepo(getcwd() ?: '.');
            if ($handoffOnly && $gitUrl === null) {
                throw new \RuntimeException('--handoff-only requires --git-url=<url>');
            }
        } catch (\Throwable $error) {
            fwrite(STDERR, 'duo: onboard: ' . $error->getMessage() . "\n");
            return 1;
        }

        $adopt = $steps['adopt'] ?? static fn(EnvironmentDriver $target, array $args, string $root): int =>
            AdoptCommand::run($target, $args, $root);
        $assess = $steps['assess'] ?? static fn(EnvironmentDriver $target, array $args, string $root): int =>
            AssessCommand::run($target, $args, $root);
        $status = $steps['status'] ?? static fn(EnvironmentDriver $environment): int => StatusCommand::run(
            $environment,
            [],
            static function (string $code, string $message, string $remediation): void {
                fwrite(STDERR, "[$code] $message\n");
                fwrite(STDERR, "remedy: $remediation\n");
            },
            static function (array $refusal): void {
                fwrite(STDERR, (string) ($refusal['message'] ?? 'status refused') . "\n");
            },
            static fn(): bool => true
        );
        $init = $steps['init'] ?? static fn(EnvironmentDriver $target, array $args): int =>
            InitCommand::run(
                $target,
                $args,
                static function (array $refusal): void {
                    $message = (string) ($refusal['message'] ?? 'initialization refused');
                    fwrite(STDERR, "duo: $message\n");
                },
                $status,
                static fn(): mixed => fgets(STDIN),
                false
            );
        $handoffPreflight = $steps['handoff_preflight'] ?? self::preflightHandoff(...);
        $handoff = $steps['handoff'] ?? self::publishAndCheckout(...);

        if ($handoffOnly) {
            try {
                $branch = isset($steps['handoff'])
                    ? $handoff($driver, $workspace, (string) $gitUrl)
                    : self::publishAndCheckout($driver, $workspace, (string) $gitUrl);
            } catch (\Throwable $error) {
                fwrite(STDERR, 'duo: onboard handoff: ' . $error->getMessage() . "\n");
                return 1;
            }
            self::renderHandoffSuccess($sourceRoot, $driver, $branch);
            return 0;
        }

        $preflightReceipt = null;
        if ($gitUrl !== null) {
            try {
                // Credentials, remote emptiness, local generated bytes and
                // origin consistency are all answerable before adopt/init.
                $preflightReceipt = self::assertPristineLocalCheckout($workspace);
                $handoffPreflight($driver, $workspace, $gitUrl);
            } catch (\Throwable $error) {
                fwrite(STDERR, 'duo: onboard handoff preflight: ' . $error->getMessage() . "\n");
                return 1;
            }
        }

        echo "Onboarding 1/3: install Duo transactionally.\n";
        $exit = $adopt($driver, [], $sourceRoot);
        if ($exit !== 0) {
            return $exit;
        }
        echo "Onboarding 2/3: assess the installed site without changing managed state.\n";
        $exit = $assess($driver, [], $sourceRoot);
        if ($exit !== 0) {
            return $exit;
        }
        $handoffReceipt = null;
        if ($preflightReceipt !== null) {
            try {
                $handoffReceipt = self::assessmentReceipt($workspace, $preflightReceipt);
            } catch (\Throwable $error) {
                fwrite(STDERR, 'duo: onboard handoff: ' . $error->getMessage() . "\n");
                return 1;
            }
        }
        echo "Onboarding 3/3: review and initialize the managed baseline.\n";
        $exit = $init($driver, $initArgs);
        if ($exit !== 0) {
            return $exit;
        }
        if ($handoffReceipt !== null) {
            try {
                self::assertPristineLocalCheckout($workspace, $handoffReceipt);
            } catch (\Throwable $error) {
                fwrite(STDERR, 'duo: onboard handoff: ' . $error->getMessage() . "\n");
                return 1;
            }
        }

        if ($gitUrl !== null) {
            try {
                $branch = isset($steps['handoff'])
                    ? $handoff($driver, $workspace, $gitUrl)
                    : self::publishAndCheckout($driver, $workspace, $gitUrl, $handoffReceipt);
            } catch (\Throwable $error) {
                fwrite(STDERR, 'duo: onboard handoff: ' . $error->getMessage() . "\n");
                return 1;
            }
            self::renderHandoffSuccess($sourceRoot, $driver, $branch);
        } else {
            $cli = realpath($sourceRoot . '/cli/duo') ?: $sourceRoot . '/cli/duo';
            echo "Initialized successfully. Publish it later without repeating adopt/assess/init:\n";
            echo '  ' . escapeshellarg($cli) . ' onboard ' . escapeshellarg($driver->name())
                . " --handoff-only --git-url=<empty-remote-url>\n";
            echo "The URL must be reachable with Git credentials from both this controller and the WordPress target.\n";
        }
        return 0;
    }

    /** @return array{0:list<string>,1:?string,2:bool} */
    public static function options(array $extra): array {
        $init = [];
        $gitUrl = null;
        $handoffOnly = false;
        foreach ($extra as $arg) {
            if ($arg === '--handoff-only') {
                if ($handoffOnly) {
                    throw new \RuntimeException('--handoff-only was supplied more than once');
                }
                $handoffOnly = true;
                continue;
            }
            if (is_string($arg) && str_starts_with($arg, '--git-url=')) {
                if ($gitUrl !== null) {
                    throw new \RuntimeException('--git-url was supplied more than once');
                }
                $gitUrl = substr($arg, strlen('--git-url='));
                if ($gitUrl === '' || preg_match('/[\x00-\x1f\x7f]/', $gitUrl) === 1) {
                    throw new \RuntimeException('--git-url requires a non-empty URL without control bytes');
                }
                continue;
            }
            $init[] = $arg;
        }
        if ($handoffOnly && $init !== []) {
            throw new \RuntimeException('--handoff-only accepts no init flags');
        }
        return [$init, $gitUrl, $handoffOnly];
    }

    private static function preflightHandoff(
        EnvironmentDriver $driver,
        string $workspace,
        string $gitUrl
    ): void {
        self::assertLocalBoundary($workspace);
        self::assertLocalOrigin($workspace, $gitUrl);
        $local = self::runGitTransfer(['git', 'ls-remote', '--refs', $gitUrl]);
        if ($local['exit'] !== 0) {
            throw new \RuntimeException('controller cannot authenticate to the Git remote: ' . trim($local['stderr']));
        }
        if (trim($local['stdout']) !== '') {
            throw new \RuntimeException('Git remote is not empty; use a new empty remote for initial publication');
        }
        $q = static fn(string $value): string => escapeshellarg($value);
        $target = self::captureTargetRaw(
            $driver,
            'git ls-remote --refs ' . $q($gitUrl),
            self::TARGET_PROBE_TIMEOUT_MILLISECONDS,
            self::TARGET_PROBE_OUTPUT_LIMIT_BYTES
        );
        if ($target['exit'] !== 0) {
            throw new \RuntimeException('target cannot authenticate to the Git remote: ' . trim($target['stderr']));
        }
        if (trim($target['stdout']) !== '') {
            throw new \RuntimeException('Git remote became non-empty during target credential preflight');
        }
    }

    private static function publishAndCheckout(
        EnvironmentDriver $driver,
        string $workspace,
        string $gitUrl,
        ?array $expectedReceipt = null
    ): string {
        self::assertLocalBoundary($workspace);
        $initialReceipt = self::assertPristineLocalCheckout($workspace, $expectedReceipt);
        self::assertLocalOrigin($workspace, $gitUrl);
        $repo = $driver->repoPath();
        $q = static fn(string $value): string => escapeshellarg($value);
        $script = 'set -eu; repo=' . $q($repo) . '; url=' . $q($gitUrl) . '; '
            . 'test -d "$repo/.git"; '
            . 'branch=$(git -C "$repo" symbolic-ref --quiet --short HEAD) || '
            . '{ echo "target Git worktree has detached HEAD" >&2; exit 1; }; '
            . 'git check-ref-format --branch "$branch" >/dev/null; '
            . 'receipt_ref="refs/duo/handoff/$branch"; '
            . 'origin_missing=0; if git -C "$repo" remote get-url origin >/dev/null 2>&1; then '
            . 'test "$(git -C "$repo" remote get-url --all origin)" = "$url" || '
            . '{ echo "target origin URL does not match --git-url" >&2; exit 1; }; '
            . 'test "$(git -C "$repo" remote get-url --push --all origin)" = "$url" || '
            . '{ echo "target origin push URL does not match --git-url" >&2; exit 1; }; '
            . 'else origin_missing=1; fi; '
            . 'if head=$(git -C "$repo" rev-parse --verify HEAD 2>/dev/null); then '
            . 'receipt=$(git -C "$repo" rev-parse --verify "$receipt_ref" 2>/dev/null) || '
            . '{ echo "target history is not an owned Duo handoff revision" >&2; exit 1; }; '
            . 'test "$head" = "$receipt" || { echo "target handoff receipt does not match HEAD" >&2; exit 1; }; '
            . 'git -C "$repo" for-each-ref --format="%(refname) %(objectname)" | '
            . 'awk -v branch="$branch" -v head="$head" \''
            . '$1 == "refs/heads/" branch && $2 == head { next } '
            . '$1 == "refs/duo/handoff/" branch && $2 == head { next } '
            . '$1 == "refs/remotes/origin/" branch && $2 == head { next } '
            . '{ exit 1 }\' || { echo "target Git refs exceed the owned handoff boundary" >&2; exit 1; }; '
            . 'test -z "$(git -C "$repo" status --porcelain -- .gitignore site.duo.json code state media)" || '
            . '{ echo "target managed publication tree changed after its handoff receipt" >&2; exit 1; }; '
            . 'else '
            . 'test -z "$(git -C "$repo" for-each-ref --format="%(refname)")" || '
            . '{ echo "target repository has refs before initial publication" >&2; exit 1; }; '
            . 'test -z "$(git -C "$repo" ls-files)" || '
            . '{ echo "target index is not empty before initial publication" >&2; exit 1; }; '
            . 'git -C "$repo" add .gitignore site.duo.json code state media; '
            . 'staged=$(git -C "$repo" diff --cached --name-only); '
            . 'while IFS= read -r path; do case "$path" in '
            . '.gitignore|site.duo.json|code/*|state/*|media/*) ;; '
            . '*) echo "target staged path exceeds the managed publication boundary: $path" >&2; exit 1 ;; esac; '
            . "done <<DUO_STAGED\n\$staged\nDUO_STAGED\n"
            . 'tree=$(git -C "$repo" write-tree); '
            . 'head=$(git -C "$repo" -c user.name=duo -c user.email=duo@example.test '
            . 'commit-tree "$tree" -m "duo: initial managed baseline"); '
            . 'printf "start\\ncreate refs/heads/%s %s\\ncreate %s %s\\nprepare\\ncommit\\n" '
            . '"$branch" "$head" "$receipt_ref" "$head" | git -C "$repo" update-ref --stdin; fi; '
            . 'remote=$(git -C "$repo" ls-remote --refs "$url"); '
            . 'expected=$(printf "%s\\trefs/heads/%s" "$head" "$branch"); '
            . 'if [ -n "$remote" ] && [ "$remote" != "$expected" ]; then '
            . 'echo "Git remote contains refs outside the exact prior Duo publication" >&2; exit 1; fi; '
            . 'git -C "$repo" push "$url" "$head:refs/heads/$branch"; '
            . 'if [ "$origin_missing" -eq 1 ]; then git -C "$repo" remote add origin "$url"; fi; '
            . 'git -C "$repo" fetch origin "$branch"; '
            . 'git -C "$repo" branch --set-upstream-to="origin/$branch" "$branch" >/dev/null; '
            . 'printf "DUO_HANDOFF %s %s\\n" "$branch" "$head"';
        $target = self::captureTargetRaw(
            $driver,
            $script,
            self::GIT_TRANSFER_TIMEOUT_MILLISECONDS,
            self::GIT_TRANSFER_OUTPUT_LIMIT_BYTES
        );
        if ($target['exit'] !== 0) {
            throw new \RuntimeException('target Git publish failed: ' . trim($target['stderr']));
        }
        if (preg_match('/^DUO_HANDOFF ([^\s]+) ([a-f0-9]{40})$/m', $target['stdout'], $published) !== 1) {
            throw new \RuntimeException('target Git publish returned no branch/revision receipt');
        }
        $branch = $published[1];
        $revision = $published[2];

        self::assertPristineLocalCheckout($workspace, $initialReceipt);
        self::ensureLocalOrigin($workspace, $gitUrl);
        $remoteRef = 'refs/remotes/origin/' . $branch;
        $fetch = self::runGitTransfer([
            'git', '-C', $workspace, 'fetch', '--no-tags', 'origin',
            '+refs/heads/' . $branch . ':' . $remoteRef,
        ]);
        if ($fetch['exit'] !== 0) {
            throw new \RuntimeException('local Git fetch failed: ' . trim($fetch['stderr']));
        }
        $fetched = HostProcess::run(['git', '-C', $workspace, 'rev-parse', '--verify', $remoteRef]);
        if ($fetched['exit'] !== 0 || trim($fetched['stdout']) !== $revision) {
            throw new \RuntimeException('fetched branch moved after the target publication receipt; local boundary was not changed');
        }

        self::assertLocalBoundary($workspace);
        self::assertPristineLocalCheckout($workspace, $initialReceipt);
        $token = bin2hex(random_bytes(16));
        $backups = [
            $workspace . '/site.duo.json' => $workspace . '/.git/duo-handoff-site-' . $token,
            $workspace . '/.gitignore' => $workspace . '/.git/duo-handoff-ignore-' . $token,
        ];
        $moved = [];
        $checkoutSucceeded = false;
        try {
            foreach ($backups as $path => $backup) {
                if (!rename($path, $backup)) {
                    throw new \RuntimeException("could not stage local generated boundary $path");
                }
                $moved[$path] = $backup;
            }
            $checkout = self::runGitTransfer(
                ['git', '-C', $workspace, 'checkout', '-b', $branch, '--track', $remoteRef]
            );
            if ($checkout['exit'] !== 0) {
                throw new \RuntimeException('local Git checkout failed: ' . trim($checkout['stderr']));
            }
            $checkoutSucceeded = true;
            $head = HostProcess::run(['git', '-C', $workspace, 'rev-parse', 'HEAD']);
            if ($head['exit'] !== 0 || trim($head['stdout']) !== $revision) {
                throw new \RuntimeException('local checkout does not match the target publication receipt');
            }
            if ($initialReceipt['duo'] !== null
                && self::localTreeReceipt($workspace . '/.duo') !== $initialReceipt['duo']) {
                throw new \RuntimeException('local assessment artifacts changed during checkout');
            }
        } catch (\Throwable $error) {
            if ($checkoutSucceeded) {
                throw new \RuntimeException(
                    $error->getMessage() . '; checkout changed after publication; generated-boundary backups were retained in .git'
                );
            }
            try {
                self::restoreGeneratedBoundary($workspace, $moved);
            } catch (\Throwable $rollback) {
                throw new \RuntimeException(
                    $error->getMessage() . '; generated-boundary restoration paused: ' . $rollback->getMessage()
                );
            }
            throw $error;
        }
        foreach ($backups as $backup) {
            if (is_file($backup) && !is_link($backup) && !unlink($backup)) {
                throw new \RuntimeException("checkout succeeded but generated-boundary backup cleanup failed: $backup");
            }
        }
        return $branch;
    }

    private static function assertLocalBoundary(string $workspace): void {
        self::assertGeneratedFile($workspace . '/site.duo.json', Adopt::repositorySeedBytes());
        self::assertGeneratedFile($workspace . '/.gitignore', Adopt::repositoryGitignoreBytes());
    }

    /**
     * @param ?array{branch:string,paths:array<string,array<string,mixed>>,duo:?array<int,array<string,mixed>>} $expected
     * @return array{branch:string,paths:array<string,array<string,mixed>>,duo:?array<int,array<string,mixed>>}
     */
    private static function assertPristineLocalCheckout(string $workspace, ?array $expected = null): array {
        if (is_link($workspace . '/.git') || !is_dir($workspace . '/.git')
            || is_link($workspace . '/.duo-envs.json') || !is_file($workspace . '/.duo-envs.json')) {
            throw new \RuntimeException('local workspace control boundary is not ordinary');
        }
        $entries = array_values(array_diff(scandir($workspace) ?: [], ['.', '..']));
        sort($entries, SORT_STRING);
        $allowed = ['.duo-envs.json', '.git', '.gitignore', 'site.duo.json'];
        if (in_array('.duo', $entries, true)) {
            $allowed[] = '.duo';
            sort($allowed, SORT_STRING);
            if (is_link($workspace . '/.duo') || !is_dir($workspace . '/.duo')) {
                throw new \RuntimeException('local assessment artifact boundary is not an ordinary directory');
            }
            $duoEntries = array_values(array_diff(scandir($workspace . '/.duo') ?: [], ['.', '..']));
            if ($duoEntries !== ['contract'] || is_link($workspace . '/.duo/contract')
                || !is_dir($workspace . '/.duo/contract')) {
                throw new \RuntimeException('local .duo boundary contains artifacts outside the assessment contract directory');
            }
        }
        if ($entries !== $allowed) {
            throw new \RuntimeException('local workspace changed before handoff; expected only connect and assessment artifacts');
        }
        $head = HostProcess::run(['git', '-C', $workspace, 'rev-parse', '--verify', 'HEAD']);
        $heads = HostProcess::run(['git', '-C', $workspace, 'for-each-ref', '--format=%(refname)', 'refs/heads']);
        $index = HostProcess::run(['git', '-C', $workspace, 'ls-files']);
        $branch = HostProcess::run(['git', '-C', $workspace, 'symbolic-ref', '--quiet', '--short', 'HEAD']);
        if ($head['exit'] === 0 || $heads['exit'] !== 0 || trim($heads['stdout']) !== ''
            || $index['exit'] !== 0 || trim($index['stdout']) !== ''
            || $branch['exit'] !== 0 || trim($branch['stdout']) === '') {
            throw new \RuntimeException('local workspace Git state is no longer the empty connect boundary');
        }
        $paths = [];
        foreach (['.duo-envs.json', '.git', '.gitignore', 'site.duo.json'] as $relative) {
            $paths[$relative] = self::localPathIdentity($workspace . '/' . $relative);
        }
        $receipt = [
            'branch' => trim($branch['stdout']),
            'paths' => $paths,
            'duo' => in_array('.duo', $entries, true) ? self::localTreeReceipt($workspace . '/.duo') : null,
        ];
        if ($expected !== null && $receipt !== $expected) {
            throw new \RuntimeException('local workspace changed during target publication; local boundary was not moved');
        }
        return $receipt;
    }

    /**
     * Assessment may add exactly one ignored `.duo/contract` tree. The
     * connect-created registry, Git boundary, seeds, and branch remain the
     * authority captured before target code is installed or bootstrapped.
     *
     * @param array{branch:string,paths:array<string,array<string,mixed>>,duo:?array<int,array<string,mixed>>} $before
     * @return array{branch:string,paths:array<string,array<string,mixed>>,duo:?array<int,array<string,mixed>>}
     */
    private static function assessmentReceipt(string $workspace, array $before): array {
        $after = self::assertPristineLocalCheckout($workspace);
        if ($after['branch'] !== $before['branch'] || $after['paths'] !== $before['paths']
            || ($before['duo'] !== null && $after['duo'] !== $before['duo'])) {
            throw new \RuntimeException('local connect authority changed during adoption or assessment');
        }
        return $after;
    }

    /** @param array<string,string> $backups */
    private static function restoreGeneratedBoundary(string $workspace, array $backups): void {
        foreach ($backups as $path => $backup) {
            if (file_exists($path) || is_link($path)) {
                throw new \RuntimeException("local checkout wrote $path; it and backup $backup were retained");
            }
            if (!is_file($backup) || is_link($backup) || !rename($backup, $path)) {
                throw new \RuntimeException("could not restore generated boundary: $path");
            }
        }
        self::assertLocalBoundary($workspace);
    }

    /** @return array{dev:string,ino:string,type:string,size:string,sha256:?string} */
    private static function localPathIdentity(string $path): array {
        $stat = lstat($path);
        if (!is_array($stat) || is_link($path) || (!is_dir($path) && !is_file($path))) {
            throw new \RuntimeException("local retained path is not ordinary: $path");
        }
        return [
            'dev' => (string) $stat['dev'],
            'ino' => (string) $stat['ino'],
            'type' => is_dir($path) ? 'directory' : 'file',
            'size' => is_file($path) ? (string) $stat['size'] : '0',
            'sha256' => is_file($path) ? hash_file('sha256', $path) : null,
        ];
    }

    /** @return list<array<string,mixed>> */
    private static function localTreeReceipt(string $root): array {
        $rows = [['path' => '.', 'identity' => self::localPathIdentity($root)]];
        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($root, \FilesystemIterator::SKIP_DOTS),
            \RecursiveIteratorIterator::SELF_FIRST
        );
        foreach ($iterator as $entry) {
            $path = $entry->getPathname();
            if ($entry->isLink() || (!$entry->isDir() && !$entry->isFile())) {
                throw new \RuntimeException("local assessment artifact is not ordinary: $path");
            }
            $rows[] = [
                'path' => substr($path, strlen($root) + 1),
                'identity' => self::localPathIdentity($path),
            ];
        }
        usort($rows, static fn(array $left, array $right): int => $left['path'] <=> $right['path']);
        return $rows;
    }

    /** @return array{exit:int,stdout:string,stderr:string} */
    private static function runGitTransfer(array $argv): array {
        return HostProcess::run(
            $argv,
            null,
            [],
            false,
            self::GIT_TRANSFER_TIMEOUT_MILLISECONDS,
            self::GIT_TRANSFER_OUTPUT_LIMIT_BYTES
        );
    }

    /** @return array{exit:int,stdout:string,stderr:string} */
    private static function captureTargetRaw(
        EnvironmentDriver $driver,
        string $script,
        int $timeoutMilliseconds,
        int $outputLimitBytes
    ): array {
        if (!$driver instanceof Transport) {
            throw new \RuntimeException('onboard requires a transport with bounded target control');
        }
        return $driver->captureRawBounded(
            $script,
            $timeoutMilliseconds,
            $outputLimitBytes,
            $outputLimitBytes
        );
    }

    private static function assertLocalOrigin(string $workspace, string $gitUrl): void {
        $origin = HostProcess::run(['git', '-C', $workspace, 'remote', 'get-url', 'origin']);
        if ($origin['exit'] !== 0) {
            if ($origin['exit'] === 2) {
                return;
            }
            throw new \RuntimeException('could not inspect the local origin: ' . trim($origin['stderr']));
        }
        foreach ([
            ['git', '-C', $workspace, 'remote', 'get-url', '--all', 'origin'],
            ['git', '-C', $workspace, 'remote', 'get-url', '--push', '--all', 'origin'],
        ] as $command) {
            $urls = HostProcess::run($command);
            if ($urls['exit'] !== 0 || self::urlLines($urls['stdout']) !== [$gitUrl]) {
                throw new \RuntimeException('local origin fetch/push URLs do not match --git-url');
            }
        }
    }

    private static function ensureLocalOrigin(string $workspace, string $gitUrl): void {
        $origin = HostProcess::run(['git', '-C', $workspace, 'remote', 'get-url', 'origin']);
        if ($origin['exit'] === 0) {
            self::assertLocalOrigin($workspace, $gitUrl);
            return;
        }
        if ($origin['exit'] !== 2) {
            throw new \RuntimeException('could not inspect the local origin: ' . trim($origin['stderr']));
        }
        $add = HostProcess::run(['git', '-C', $workspace, 'remote', 'add', 'origin', $gitUrl]);
        if ($add['exit'] !== 0) {
            throw new \RuntimeException('could not configure local origin: ' . trim($add['stderr']));
        }
        self::assertLocalOrigin($workspace, $gitUrl);
    }

    /** @return list<string> */
    private static function urlLines(string $stdout): array {
        $trimmed = trim($stdout);
        return $trimmed === '' ? [] : (preg_split('/\R/', $trimmed) ?: []);
    }

    private static function renderHandoffSuccess(
        string $sourceRoot,
        EnvironmentDriver $driver,
        string $branch
    ): void {
        $cli = realpath($sourceRoot . '/cli/duo') ?: $sourceRoot . '/cli/duo';
        echo "Published the initialized target baseline and checked out branch $branch in this workspace.\n";
        echo "Next: inspect the initialized target through the configured environment:\n";
        echo '  ' . escapeshellarg($cli) . ' assess ' . escapeshellarg($driver->name()) . "\n";
        echo "Capture always writes to the target repo_path ({$driver->repoPath()}), not this local checkout.\n";
        echo "Before feature-branch capture, point or materialize the target to that branch; see docs/guides/daily-workflow.md.\n";
        echo "Disposable preview creation additionally requires two configured environments and providers; see docs/guides/release.md.\n";
    }

    private static function assertGeneratedFile(string $path, string $expected): void {
        if (is_link($path) || !is_file($path) || file_get_contents($path) !== $expected) {
            throw new \RuntimeException("local generated boundary changed; refusing to replace $path");
        }
    }

}
