#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * Generate the committed runtime inventory of shipped adapter names.
 *
 * The names are security data: they are the exact unprefixed identities an
 * out-of-tree adapter may use only as a reviewed override. They must therefore
 * be available to the dependency-free agent without scanning a source tree,
 * but asking every adapter author to copy a new slug into agent code created a
 * second catalog. This generator keeps the runtime list closed while deriving
 * its membership from the package/platform source of truth. Release-gate
 * byte-compares the committed output before a release can ship.
 *
 * The `id_kind` grandfather floor deliberately remains hand-reviewed in
 * IdentityNamespaces: removing an id kind from the current library must never
 * erase a value already embedded in customer branches and wprism_map rows.
 * Adapter names have the opposite invariant—the reserved set is exactly the
 * library that ships in this release—so derivation is the honest mechanism.
 *
 * Usage:
 *   php tools/shipped-identity-inventory.php
 *   php tools/shipped-identity-inventory.php --check
 *   php tools/shipped-identity-inventory.php --print
 *   php tools/shipped-identity-inventory.php --root=/path/to/tree
 */

require_once __DIR__ . '/../agent/src/Policy/AdapterLibrary.php';

const SII_OUTPUT = 'agent/src/Adapter/ShippedIdentityInventory.php';

/** @return list<string> */
function sii_adapter_names(string $root): array
{
    $library = \WPrism\AdapterLibrary::fromSourceTree($root);
    $names = [];
    foreach ($library->packages() as $package) {
        $name = $package->name();
        if (isset($names[$name])) {
            throw new RuntimeException("duplicate shipped adapter name '$name'");
        }
        $names[$name] = true;
    }
    $names = array_keys($names);
    sort($names, SORT_STRING);
    if ($names === []) {
        throw new RuntimeException('shipped adapter library is empty');
    }

    return $names;
}

/** @param list<string> $names */
function sii_render(array $names): string
{
    $rows = '';
    foreach ($names as $name) {
        if (preg_match('/^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/D', $name) !== 1) {
            throw new RuntimeException("shipped adapter name is not canonical: '$name'");
        }
        $rows .= "        '$name',\n";
    }

    return <<<PHP
<?php
declare(strict_types=1);

namespace WPrism;

/**
 * GENERATED by tools/shipped-identity-inventory.php — do not edit.
 *
 * Dependency-free runtime projection of the package/platform source tree.
 * Regenerate with: php tools/shipped-identity-inventory.php
 */
final class ShippedIdentityInventory
{
    /** @var list<string> */
    public const ADAPTER_NAMES = [
{$rows}    ];
}

PHP;
}

/** @return array{root:string,mode:string} */
function sii_options(array $argv): array
{
    $root = dirname(__DIR__);
    $mode = 'write';
    foreach (array_slice($argv, 1) as $arg) {
        if ($arg === '--check') {
            if ($mode !== 'write') {
                throw new RuntimeException('choose exactly one of --check or --print');
            }
            $mode = 'check';
            continue;
        }
        if ($arg === '--print') {
            if ($mode !== 'write') {
                throw new RuntimeException('choose exactly one of --check or --print');
            }
            $mode = 'print';
            continue;
        }
        if (str_starts_with($arg, '--root=')) {
            $root = substr($arg, strlen('--root='));
            continue;
        }
        throw new RuntimeException("unknown argument '$arg'");
    }
    $canonical = realpath($root);
    if ($canonical === false || !is_dir($canonical)) {
        throw new RuntimeException("repository root is not a directory: '$root'");
    }

    return ['root' => $canonical, 'mode' => $mode];
}

function sii_main(array $argv): int
{
    try {
        $options = sii_options($argv);
        $bytes = sii_render(sii_adapter_names($options['root']));
        $path = $options['root'] . '/' . SII_OUTPUT;
        if ($options['mode'] === 'print') {
            echo $bytes;
            return 0;
        }
        if ($options['mode'] === 'check') {
            $current = is_file($path) ? (string) file_get_contents($path) : '';
            if ($current !== $bytes) {
                fwrite(STDERR, SII_OUTPUT . " is stale; regenerate with: php tools/shipped-identity-inventory.php\n");
                return 1;
            }
            echo 'ok    ' . SII_OUTPUT . "\n";
            return 0;
        }

        $directory = dirname($path);
        if (!is_dir($directory)) {
            throw new RuntimeException("output directory is absent: '$directory'");
        }
        $temporary = $path . '.tmp.' . getmypid();
        if (file_put_contents($temporary, $bytes, LOCK_EX) !== strlen($bytes)
            || !rename($temporary, $path)) {
            @unlink($temporary);
            throw new RuntimeException('could not atomically publish ' . SII_OUTPUT);
        }
        echo 'wrote ' . SII_OUTPUT . ' (' . count(sii_adapter_names($options['root'])) . " adapter names)\n";
        return 0;
    } catch (Throwable $failure) {
        fwrite(STDERR, 'shipped-identity-inventory: ' . $failure->getMessage() . "\n");
        return 1;
    }
}

if (realpath($_SERVER['SCRIPT_FILENAME'] ?? '') === __FILE__) {
    $arguments = isset($_SERVER['argv']) && is_array($_SERVER['argv']) ? $_SERVER['argv'] : [];
    exit(sii_main($arguments));
}
